# Generated by Django 6.0.6 on 2026-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_userprofile_favorite_team_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprediction',
            name='actual_result',
        ),
        migrations.RemoveField(
            model_name='userprediction',
            name='correct_prediction',
        ),
        migrations.RemoveField(
            model_name='userprediction',
            name='match',
        ),
        migrations.RemoveField(
            model_name='userprediction',
            name='user_prediction',
        ),
        migrations.AddField(
            model_name='userprediction',
            name='away_team',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprediction',
            name='home_team',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
