# Generated by Django 6.0.6 on 2026-06-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_userprediction_v3_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprediction',
            name='p_away',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprediction',
            name='p_draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprediction',
            name='p_home',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprediction',
            name='predicted_result',
            field=models.CharField(max_length=50),
        ),
    ]
